rockthejvm {
  db {
    poolName = "quill"
    maximumPoolSize = 5
    connectionTimeout = 30000
    transactionIsolation = TRANSACTION_SERIALIZABLE
    dataSourceClassName = org.postgresql.ds.PGSimpleDataSource
    dataSource {
      url = "jdbc:postgresql://localhost:5432/reviewboard"
      url = ${?DATABASE_JDBC_URL}
      user = "docker"
      user = ${?DATABASE_USER}
      password = "docker"
      password = ${?DATABASE_PASS}
    }
  }
  jwt {
    secret = "myscret"
    secret = ${?JWT_SECRET}
    timeToLive = 864000
    timeToLive = ${?JWT_TTL}
  }
  recoveryTokens {
    duration = 600 # seconds
  }
  email {
    host = "smtp.ethereal.email"
    port = 587
    user = "kristy.kling@ethereal.email"
    pass = "gns5pyaGs2fA3qusPg"
  }
  invites {
    nInvites = 200
  }
  stripe {
    key = "sk_test_51QMIm7DSev4cSlEStFZBbdkOexXhvJRbdUKGcWbfZqmyCYxbwGn1GBM3pk1LFlO6oMuJTaEwVcPQtuml5bWHUgxI0095k22ISF"
    secret = "whsec_f7a8ad771f8fece66bae1324c19858593dd8e6abf14d801ee08f011b42e42d8b"
    price = "price_1QN2AQDSev4cSlESpwtFfYP4"
    successUrl = "http://localhost:1234/profile"
    cancelUrl = "http://localhost:1234"
  }

}